/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ApiGmailThreadsListRouteImport } from './routes/api/gmail-threads-list'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as InboxChannelRouteImport } from './routes/inbox.$channel'
import { Route as ApiPublicN8nConversationRouteImport } from './routes/api/public/n8n-conversation'
import { Route as ApiPublicN8nLogsRouteImport } from './routes/api/public/n8n-logs'
import { Route as ApiPublicTelerivetImportRouteImport } from './routes/api/public/telerivet-import'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailThreadsListRoute = ApiGmailThreadsListRouteImport.update({
  id: '/api/gmail-threads-list',
  path: '/api/gmail-threads-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxChannelRoute = InboxChannelRouteImport.update({
  id: '/inbox/$channel',
  path: '/inbox/$channel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nConversationRoute =
  ApiPublicN8nConversationRouteImport.update({
    id: '/api/public/n8n-conversation',
    path: '/api/public/n8n-conversation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicN8nLogsRoute = ApiPublicN8nLogsRouteImport.update({
  id: '/api/public/n8n-logs',
  path: '/api/public/n8n-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelerivetImportRoute =
  ApiPublicTelerivetImportRouteImport.update({
    id: '/api/public/telerivet-import',
    path: '/api/public/telerivet-import',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/queue': typeof QueueRoute
  '/reports': typeof ReportsRoute
  '/api/gmail-threads-list': typeof ApiGmailThreadsListRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/inbox/$channel': typeof InboxChannelRoute
  '/clients/': typeof ClientsIndexRoute
  '/api/public/n8n-conversation': typeof ApiPublicN8nConversationRoute
  '/api/public/n8n-logs': typeof ApiPublicN8nLogsRoute
  '/api/public/telerivet-import': typeof ApiPublicTelerivetImportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/queue': typeof QueueRoute
  '/reports': typeof ReportsRoute
  '/api/gmail-threads-list': typeof ApiGmailThreadsListRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/inbox/$channel': typeof InboxChannelRoute
  '/clients': typeof ClientsIndexRoute
  '/api/public/n8n-conversation': typeof ApiPublicN8nConversationRoute
  '/api/public/n8n-logs': typeof ApiPublicN8nLogsRoute
  '/api/public/telerivet-import': typeof ApiPublicTelerivetImportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/queue': typeof QueueRoute
  '/reports': typeof ReportsRoute
  '/api/gmail-threads-list': typeof ApiGmailThreadsListRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/inbox/$channel': typeof InboxChannelRoute
  '/clients/': typeof ClientsIndexRoute
  '/api/public/n8n-conversation': typeof ApiPublicN8nConversationRoute
  '/api/public/n8n-logs': typeof ApiPublicN8nLogsRoute
  '/api/public/telerivet-import': typeof ApiPublicTelerivetImportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/queue'
    | '/reports'
    | '/api/gmail-threads-list'
    | '/clients/$clientId'
    | '/inbox/$channel'
    | '/clients/'
    | '/api/public/n8n-conversation'
    | '/api/public/n8n-logs'
    | '/api/public/telerivet-import'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/queue'
    | '/reports'
    | '/api/gmail-threads-list'
    | '/clients/$clientId'
    | '/inbox/$channel'
    | '/clients'
    | '/api/public/n8n-conversation'
    | '/api/public/n8n-logs'
    | '/api/public/telerivet-import'
  id:
    | '__root__'
    | '/'
    | '/queue'
    | '/reports'
    | '/api/gmail-threads-list'
    | '/clients/$clientId'
    | '/inbox/$channel'
    | '/clients/'
    | '/api/public/n8n-conversation'
    | '/api/public/n8n-logs'
    | '/api/public/telerivet-import'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QueueRoute: typeof QueueRoute
  ReportsRoute: typeof ReportsRoute
  ApiGmailThreadsListRoute: typeof ApiGmailThreadsListRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  InboxChannelRoute: typeof InboxChannelRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  ApiPublicN8nConversationRoute: typeof ApiPublicN8nConversationRoute
  ApiPublicN8nLogsRoute: typeof ApiPublicN8nLogsRoute
  ApiPublicTelerivetImportRoute: typeof ApiPublicTelerivetImportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail-threads-list': {
      id: '/api/gmail-threads-list'
      path: '/api/gmail-threads-list'
      fullPath: '/api/gmail-threads-list'
      preLoaderRoute: typeof ApiGmailThreadsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$channel': {
      id: '/inbox/$channel'
      path: '/inbox/$channel'
      fullPath: '/inbox/$channel'
      preLoaderRoute: typeof InboxChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n-conversation': {
      id: '/api/public/n8n-conversation'
      path: '/api/public/n8n-conversation'
      fullPath: '/api/public/n8n-conversation'
      preLoaderRoute: typeof ApiPublicN8nConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n-logs': {
      id: '/api/public/n8n-logs'
      path: '/api/public/n8n-logs'
      fullPath: '/api/public/n8n-logs'
      preLoaderRoute: typeof ApiPublicN8nLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telerivet-import': {
      id: '/api/public/telerivet-import'
      path: '/api/public/telerivet-import'
      fullPath: '/api/public/telerivet-import'
      preLoaderRoute: typeof ApiPublicTelerivetImportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QueueRoute: QueueRoute,
  ReportsRoute: ReportsRoute,
  ApiGmailThreadsListRoute: ApiGmailThreadsListRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  InboxChannelRoute: InboxChannelRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  ApiPublicN8nConversationRoute: ApiPublicN8nConversationRoute,
  ApiPublicN8nLogsRoute: ApiPublicN8nLogsRoute,
  ApiPublicTelerivetImportRoute: ApiPublicTelerivetImportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
